### ISSUE TITLE
Support for multiple images 

### ISSUE THREAD

**Issue by amyzx** [Conzel/convolutions-rs#1]
Hi, I am wondering whether convolve function support for many images? 

For example, I have 5 images. But if I want to compute convolve values, I need to write a for loop to iterate each image. 

Is there any other way to do conv2d like pytorch? Thanks!

By the way, can convolve support i64 data?

**Comment by Conzel** [comment]
Hey!

Currently, we do not support convolution for multiple images, but this can easily be emulated by using a for loop as you said (possibly with rayon for better performance). This does not make performance suffer in any way on CPU, Pytorch also implements convolution simply as a for-loop over the batch dimension. We might want to offer this with another function to keep a similar interface to Pytorch.

i64 is currently not supported, only Floats. But thinking about it, we can definitely do this in the near future, as we only need to really require that the types used in the convolutions support add and multiply. It might take a few weeks, as at the moment, we are still focussed on making transposed convolutions sufficiently fast for realistic use cases.

Thanks for your input!

**Comment by amyzx** [comment]
Thanks for your reply. Looking forward to your progress on this work in the future!
